import type { TwinPackage } from './types';

export const PACKAGES: TwinPackage[] = [
  {
    key: 'nucleus',
    name: 'Nucleus',
    tagline: 'Signal Scan',
    price: 'Free',
    subtitle: 'No credit card needed',
    featureBullets: [
      '15 core diagnostic questions',
      'Revenue signal overview',
      '1 constraint identified',
      'Executive summary (3 sections)',
    ],
    cta: 'Start Free',
  },
  {
    key: 'catalyst',
    name: 'Catalyst',
    tagline: 'Diagnostic Deep Dive',
    price: '$99',
    subtitle: 'One-time · Instant access',
    featureBullets: [
      '35 diagnostic questions',
      'Revenue engine + funnel',
      '3 constraints mapped',
      '6-section report',
      'Live revenue simulator',
      '30-min expert strategy call',
    ],
    cta: 'Get Catalyst',
  },
  {
    key: 'vanguard',
    name: 'Vanguard',
    tagline: 'Full Intelligence',
    price: '$199',
    subtitle: 'One-time · Instant access',
    featureBullets: [
      '55 diagnostic questions',
      'Full 9-section report',
      'AI follow-up layer (5-8 questions)',
      '5-year projection',
      'AS-IS vs TO-BE model',
      'Valuation estimate',
      '60-min expert strategy call',
    ],
    cta: 'Get Vanguard',
    featured: true,
  },
  {
    key: 'apex',
    name: 'Apex',
    tagline: 'Boardroom Grade',
    price: '$499',
    subtitle: 'One-time · Priority access',
    featureBullets: [
      'All 77+ diagnostic questions',
      'Full 11-section report',
      'AI follow-up (8-10 questions)',
      'Strategic canvas + roadmap',
      'Must-win battles framework',
      'Full simulator + projections',
      '90-min board-level review call',
    ],
    cta: 'Get Apex',
  },
];
